services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn Backend.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1],web
      - CELERY_BROKER_URL=${REDIS_URL:-redis://redis:6379/0}
      - CELERY_RESULT_BACKEND=${REDIS_URL:-redis://redis:6379/0}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - DATABASE_URL=postgres://mathia_user:mathia_password@db:5432/mathia_db
      - HF_API_TOKEN=${HF_API_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - CALENDLY_CLIENT_ID=${CALENDLY_CLIENT_ID}
      - Webhook_signing_key=${Webhook_signing_key}
      - CALENDLY_CLIENT_SECRET=${CALENDLY_CLIENT_SECRET}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - GIPHY_API_KEY=${GIPHY_API_KEY}
      - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY}
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${REDIS_URL:-redis://redis:6379/0}
      - CELERY_RESULT_BACKEND=${REDIS_URL:-redis://redis:6379/0}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - DATABASE_URL=postgres://mathia_user:mathia_password@db:5432/mathia_db

  celery_worker:
    build: .
    command: celery -A Backend worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${REDIS_URL:-redis://redis:6379/0}
      - CELERY_RESULT_BACKEND=${REDIS_URL:-redis://redis:6379/0}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - DATABASE_URL=postgres://mathia_user:mathia_password@db:5432/mathia_db
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A Backend beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${REDIS_URL:-redis://redis:6379/0}
      - CELERY_RESULT_BACKEND=${REDIS_URL:-redis://redis:6379/0}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - DATABASE_URL=postgres://mathia_user:mathia_password@db:5432/mathia_db
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
